# Generated by Django 5.0.2 on 2024-04-22 16:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('62ba0a86-0099-11ef-8ec3-9c2dcdaefecd'), editable=False, unique=True),
        ),
    ]
