# Generated by Django 5.0.2 on 2024-04-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_myuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_id',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
