# Generated by Django 5.0.2 on 2024-04-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default='test note', max_length=200),
        ),
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(default='test description', max_length=500),
        ),
    ]
